In [1]:
import numpy as np
import pandas as pd
import xarray as xr
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import pyplot as plt
import matplotlib.ticker as mticker
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
%matplotlib inline

In [2]:
beta = 1.61e-11 # m-1 s-1
L = 7e6 # m (Channel Width)
k0 = 1.5e-6 # m-1 (zonal wavenumber)
c = -2 # m s-1 (zonal phase speed)
# will use c = -5 m s-1 for part d
u0 = 0
r0 = 0

In [3]:
y = np.linspace(0, L, 16)

In [4]:
y

array([      0.        ,  466666.66666667,  933333.33333333,
       1400000.        , 1866666.66666667, 2333333.33333333,
       2800000.        , 3266666.66666667, 3733333.33333333,
       4200000.        , 4666666.66666667, 5133333.33333333,
       5600000.        , 6066666.66666667, 6533333.33333333,
       7000000.        ])

In [13]:
dy = y[1] - y[0]
dy

466666.6666666667

### 2.a.ii.
Use up-down sweep to calculate the solution throughout the grid. Plot the magnitude and phase of psi for all y_n using the radiation condition at the poleward boundary. Show that the magnitude of psi_n approaches unity (one) throughout the entire grid as the grid spacing d goes to zero, and that the magnitude of the reflection coefficient R approaches zero. (Here, just pick two small values of d and sow that the incident magnitude is close to unity and the reflection coefficient approaches zero as d is decreased.) Thus, the solution consists almost entirely (to within numerical error) of a poleward propagating wave. 


### First step is to solve for l everywhere

In [5]:
# assume without loss of generality that u_bar == 0.
lsq = ((beta/(u0 - c)) - k0**2)
lsq # get real and imaginary values but there is no imaginary component so that is why it is two values (the second one
# is zero in the debugging text file.)

5.8e-12

In [10]:
l0 = lsq**(1/2)
l0

2.408318915758459e-06

### First get a_o and b_o using equation (18)

In [15]:
a0 = (1 - (dy*l0*1j) - ((dy**2)*lsq)/2)**-1
a0

(0.2633886215268251+0.8034258014348958j)

In [16]:
b0 = (-2j * dy * l0) * (1 - (dy*l0*1j) - ((dy**2)*lsq)/2)**-1
b0

(1.805911851337122-0.5920355461240252j)

In [17]:
abs(a0)

0.8454978322628071

In [18]:
abs(b0)

1.9004798611598714

In [ ]:
an = 

In [ ]:
for z in range(0, 20):
    T_test_calc = ((So/sigma)*(0.5*(tao_inf*np.exp(-z/H)) + 1))**(1/4)
    T_test.append(T_test_calc)

In [ ]:
an = []
for j in range(0,16,1):
    an_calc = (2 - ((dy**2)*lsq) - a0(j-1))**-1
an.append(an_calc)

In [22]:
(2 - ((dy**2)*lsq) - a0)**-1

(0.5444437226596085+0.9238012401786445j)

In [37]:
N = 16

a = np.zeros((N), dtype = 'complex')
b = np.zeros((N), dtype = 'complex')

a[0] = a0
b[0] = b0

for j in np.arange(1, N, 1):
    a[j] = (2 - ((dy**2)*lsq) - a[j-1])**-1
    b[j] = b[j-1] * (2 - ((dy**2)*lsq) - a[j-1])**-1


In [38]:
a

array([0.26338862+0.8034258j , 0.54444372+0.92380124j,
       0.21612274+1.0374615j , 0.38646157+0.7699022j ,
       0.48973231+1.07596059j, 0.20279056+0.88281949j,
       0.50167447+0.82922558j, 0.31659911+1.11613938j,
       0.29547711+0.78468156j, 0.54456993+0.96806203j,
       0.19742625+0.99377019j, 0.42191694+0.77723358j,
       0.44784904+1.10512481j, 0.22151281+0.8469396j ,
       0.52433209+0.8616574j , 0.26986751+1.09398216j])

In [39]:
b

array([ 1.80591185-0.59203555j,  1.53014054+1.34597357j,
       -1.06569761+1.8783574j , -1.85800267-0.09456997j,
       -0.80817037-2.04545161j,  1.64187523-1.12826683j,
        1.7592746 +0.79546228j, -0.33086201+2.21543831j,
       -1.83617573+0.39499j   , -1.3823009 -1.56243233j,
        1.2797962 -1.68215459j,  1.84739474+0.28497107j,
        0.51242536+2.16922578j, -1.72369445+0.91450462j,
       -1.691778  -1.00572996j,  0.64369471-2.12218879j])

In [30]:
a1 = (2 - ((dy**2)*lsq) - a0)**-1
a1

(0.5444437226596085+0.9238012401786445j)

In [31]:
b1 = b0 * (2 - ((dy**2)*lsq) - a0)**-1
b1


(1.5301405428763037+1.3459735712399665j)

In [40]:
# l eventually becomes negative so then it becomes complex 


In [48]:
# now to solve for psi have to go backwards
psi = np.zeros((N), dtype = 'complex')

for j in reversed(np.arange(1, N, 1)):
    psi[j-1] = (a[j-1]*psi[j]) + b[j-1]

In [49]:
psi

array([ 1.47775129+0.87849514j,  1.53179427+0.91062266j,
       -0.34898911-0.20746741j, -1.78896047-1.0635031j ,
       -0.96927598-0.5762162j ,  1.07471177+0.63889578j,
        1.76121914+1.0470114j ,  0.22311104+0.13263529j,
       -1.59681109-0.94927393j, -1.39978339-0.8321447j ,
        0.56532626+0.33607575j,  1.81636603+1.07979519j,
        0.77313369+0.45961333j, -1.24665241-0.74111123j,
       -1.691778  -1.00572996j,  0.        +0.j        ])